export default class HttpsAgent extends https.Agent {
    static protocols: string[];
    constructor(opts: AgentOpts);
    timeout: number;
    opt: {
        keepAlive?: boolean | undefined;
        keepAliveMsecs?: number | undefined;
        maxSockets?: number | undefined;
        maxTotalSockets?: number | undefined;
        maxFreeSockets?: number | undefined;
        timeout?: number | undefined;
        scheduling?: "fifo" | "lifo" | undefined;
        port?: number;
        host?: string | undefined;
        localAddress?: string | undefined;
        localPort?: number | undefined;
        hints?: number | undefined;
        family?: number | undefined;
        lookup?: import("net").LookupFunction | undefined;
        noDelay?: boolean | undefined;
        keepAliveInitialDelay?: number | undefined;
        autoSelectFamily?: boolean | undefined;
        autoSelectFamilyAttemptTimeout?: number | undefined;
        onread?: import("net").OnReadOpts | undefined;
        rejectUnauthorized?: boolean | undefined;
        maxCachedSessions?: number | undefined;
        path?: string | undefined;
        socket?: import("stream").Duplex | undefined;
        checkServerIdentity?: typeof import("tls").checkServerIdentity | undefined;
        servername?: string | undefined;
        session?: Buffer | undefined;
        minDHSize?: number | undefined;
        pskCallback?(hint: string | null): import("tls").PSKCallbackNegotation | null;
        ALPNCallback?: ((arg: {
            servername: string;
            protocols: string[];
        }) => string | undefined) | undefined;
        ca?: string | Buffer | Array<string | Buffer> | undefined;
        cert?: string | Buffer | Array<string | Buffer> | undefined;
        sigalgs?: string | undefined;
        ciphers?: string | undefined;
        clientCertEngine?: string | undefined;
        crl?: string | Buffer | Array<string | Buffer> | undefined;
        dhparam?: string | Buffer | undefined;
        ecdhCurve?: string | undefined;
        honorCipherOrder?: boolean | undefined;
        key?: string | Buffer | Array<string | Buffer | import("tls").KeyObject> | undefined;
        privateKeyEngine?: string | undefined;
        privateKeyIdentifier?: string | undefined;
        maxVersion?: import("tls").SecureVersion | undefined;
        minVersion?: import("tls").SecureVersion | undefined;
        passphrase?: string | undefined;
        pfx?: string | Buffer | Array<string | Buffer | import("tls").PxfObject> | undefined;
        secureOptions?: number | undefined;
        secureProtocol?: string | undefined;
        sessionIdContext?: string | undefined;
        ticketKeys?: Buffer | undefined;
        sessionTimeout?: number | undefined;
        secureContext?: import("tls").SecureContext | undefined;
        enableTrace?: boolean | undefined;
        requestCert?: boolean | undefined;
        ALPNProtocols?: string[] | Uint8Array[] | Uint8Array | undefined;
        SNICallback?: ((servername: string, cb: (err: Error | null, ctx?: import("tls").SecureContext) => void) => void) | undefined;
        tunnel?: boolean;
    };
    lookup: boolean;
    proxy: import("./tunnel.js").Proxy;
    proxyOpts: any;
    tunnel: boolean;
    createConnection(opts: AgentConnectOpts, cb: (err: Error | null, s?: Duplex) => void): void;
}
export type Duplex = import("stream").Duplex;
export type AgentConnectOpts = import("./tunnel").AgentConnectOpts;
export type Proxy = import("./tunnel").Proxy;
export type AgentOpts = http.AgentOptions & https.AgentOptions & {
    proxy: string | Proxy;
    proxyOpts?: any;
    tunnel?: boolean;
};
import https from 'node:https';
import http from 'node:http';
