export default class HttpAgent extends http.Agent {
    static protocols: string[];
    constructor(opts: AgentOpts);
    timeout: number;
    opt: {
        keepAlive?: boolean | undefined;
        keepAliveMsecs?: number | undefined;
        maxSockets?: number | undefined;
        maxTotalSockets?: number | undefined;
        maxFreeSockets?: number | undefined;
        timeout?: number | undefined;
        scheduling?: "fifo" | "lifo" | undefined;
        port?: number;
        host?: string | undefined;
        localAddress?: string | undefined;
        localPort?: number | undefined;
        hints?: number | undefined;
        family?: number | undefined;
        lookup?: net.LookupFunction | undefined;
        noDelay?: boolean | undefined;
        keepAliveInitialDelay?: number | undefined;
        autoSelectFamily?: boolean | undefined;
        autoSelectFamilyAttemptTimeout?: number | undefined;
        onread?: net.OnReadOpts | undefined;
        rejectUnauthorized?: boolean | undefined;
        maxCachedSessions?: number | undefined;
        path?: string | undefined;
        socket?: import("stream").Duplex | undefined;
        checkServerIdentity?: typeof tls.checkServerIdentity | undefined;
        servername?: string | undefined;
        session?: Buffer | undefined;
        minDHSize?: number | undefined;
        pskCallback?(hint: string | null): tls.PSKCallbackNegotation | null;
        ALPNCallback?: ((arg: {
            servername: string;
            protocols: string[];
        }) => string | undefined) | undefined;
        ca?: string | Buffer | Array<string | Buffer> | undefined;
        cert?: string | Buffer | Array<string | Buffer> | undefined;
        sigalgs?: string | undefined;
        ciphers?: string | undefined;
        clientCertEngine?: string | undefined;
        crl?: string | Buffer | Array<string | Buffer> | undefined;
        dhparam?: string | Buffer | undefined;
        ecdhCurve?: string | undefined;
        honorCipherOrder?: boolean | undefined;
        key?: string | Buffer | Array<string | Buffer | tls.KeyObject> | undefined;
        privateKeyEngine?: string | undefined;
        privateKeyIdentifier?: string | undefined;
        maxVersion?: tls.SecureVersion | undefined;
        minVersion?: tls.SecureVersion | undefined;
        passphrase?: string | undefined;
        pfx?: string | Buffer | Array<string | Buffer | tls.PxfObject> | undefined;
        secureOptions?: number | undefined;
        secureProtocol?: string | undefined;
        sessionIdContext?: string | undefined;
        ticketKeys?: Buffer | undefined;
        sessionTimeout?: number | undefined;
        secureContext?: tls.SecureContext | undefined;
        enableTrace?: boolean | undefined;
        requestCert?: boolean | undefined;
        ALPNProtocols?: string[] | Uint8Array[] | Uint8Array | undefined;
        SNICallback?: ((servername: string, cb: (err: Error | null, ctx?: tls.SecureContext) => void) => void) | undefined;
    };
    lookup: boolean;
    proxy: import("./tunnel.js").Proxy;
    proxyOpts: any;
    tunnel: boolean;
    addRequest(req: http.ClientRequest, opts: AgentConnectOpts): any;
    setReqProps(req: http.ClientRequest, opts: AgentConnectOpts): void;
    createConnection(opts: AgentConnectOpts, cb: (err: Error | null, s?: Duplex) => void): void;
}
export type Duplex = import("stream").Duplex;
export type AgentConnectOpts = import("./tunnel").AgentConnectOpts & {
    hostname?: string;
    path?: string;
    pathname?: string;
    keepAlive: boolean;
};
export type Proxy = import("./tunnel").Proxy;
export type AgentOpts = http.AgentOptions & https.AgentOptions & {
    proxy: string | Proxy;
    proxyOpts?: any;
    tunnel?: boolean;
};
import http from 'node:http';
import * as net from 'node:net';
import * as tls from 'node:tls';
import https from 'node:https';
